### ISSUE TITLE
Testing uHoo air on HA 0.92.2

### ISSUE THREAD

**Issue by Clubeddie** [mcclown/home-assistant-custom-components#2]
Hi there, i am new to Home Assistant so i am starting to configurate my home devices. In case of a pilot i have a uhoo air sensor at home, with a business account. So i tried your installation on my setup. I changed a few components because of setup 0.92.2 and how sensors must be placed (2 additional files added).

Configuration check is ok, but when starting i get the next error in 
/config/home-assistant.log

2019-05-06 08:42:27 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform uhooair
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/uhooair/sensor.py", line 90, in async_setup_platform
    from pyuhooair.auth import UhooAuth
ModuleNotFoundError: No module named 'pyuhooair'

Maybe you can do something with this information. I am not a scriptkiddy. If i guess it has something to do with the python version. But don't know for sure.

If i can test things out for you, let me know!

**Comment by mcclown** [comment]
Thanks for the bug report.

There has been some changes in how HA handles custom components, with version 92. In particular how it handles dependancies like pyuhoo would be effected. I suspect you're hitting this. I haven't upgrade my instance yet but I'll see if I can do it this week and hopefully I can fix this issue for you. I'll get back to you soon.

**Comment by mcclown** [comment]
This should be resolved now. I don't have a working uhoo sensor to test against, right now but the sensor is being loaded by HA and is pulling back data, even if my data is only showing that it doesn't have any data to display.

Let me know if it is working for you now?

**Comment by Clubeddie** [comment]
Wow, first of all, what a great and fast response!!!!

I just updated the files, after restart i first get an error, but i made a typo in the mail adres. After correcting this is received the data!

So it is working over here! Great job!

In two days i get an outside sensor, maybe i can add this too.

**Comment by mcclown** [comment]
No problem, glad to hear it's sorted now. Let me know if you have any more issues.
